import 'dart:convert';

import '../models/student.dart';
import 'attendance_service.dart';
import 'checkin_service.dart';
import 'class_service.dart';
import 'student_service.dart';

/// How long a rotating QR token stays valid after it was issued.
///
/// The admin screen regenerates the payload at roughly half this interval so
/// students always have a fresh token by the time the previous one expires.
const Duration kQrTokenTtl = Duration(seconds: 60);

/// Parsed payload from a QR code generated by the academy admin.
///
/// Payload format (JSON):
/// ```
/// { "v": 1, "a": "<academyId>", "c": "<classId>", "t": <issuedAt seconds> }
/// ```
/// `t` is the Unix timestamp in seconds when the QR was rendered. The scanner
/// rejects tokens older than [kQrTokenTtl], so the admin must keep the screen
/// visible and refreshing for new tokens to be issued.
class QrPayload {
  final int version;
  final String academyId;
  final String classId;
  final int issuedAtSeconds;

  const QrPayload({
    required this.version,
    required this.academyId,
    required this.classId,
    required this.issuedAtSeconds,
  });

  /// Convenience constructor that stamps the payload with the current time.
  factory QrPayload.now({
    required String academyId,
    required String classId,
  }) {
    return QrPayload(
      version: 1,
      academyId: academyId,
      classId: classId,
      issuedAtSeconds: DateTime.now().millisecondsSinceEpoch ~/ 1000,
    );
  }

  /// Encodes the payload as the compact JSON string written to the QR.
  String encode() => jsonEncode({
        'v': version,
        'a': academyId,
        'c': classId,
        't': issuedAtSeconds,
      });

  /// Parses the payload from the QR string. Throws [FormatException] on bad input.
  factory QrPayload.parse(String raw) {
    final trimmed = raw.trim();
    if (trimmed.isEmpty) {
      throw const FormatException('QR vazio');
    }

    final Map<String, dynamic> data;
    try {
      final decoded = jsonDecode(trimmed);
      if (decoded is! Map) {
        throw const FormatException('QR invalido');
      }
      data = Map<String, dynamic>.from(decoded);
    } catch (_) {
      throw const FormatException('QR invalido');
    }

    final version = data['v'];
    final academyId = data['a'];
    final classId = data['c'];
    final issuedAt = data['t'];

    if (version is! int || version != 1) {
      throw const FormatException('Versao do QR nao suportada');
    }
    if (academyId is! String || academyId.isEmpty) {
      throw const FormatException('QR sem academia');
    }
    if (classId is! String || classId.isEmpty) {
      throw const FormatException('QR sem turma');
    }
    if (issuedAt is! int || issuedAt <= 0) {
      throw const FormatException('QR sem timestamp');
    }

    return QrPayload(
      version: version,
      academyId: academyId,
      classId: classId,
      issuedAtSeconds: issuedAt,
    );
  }
}

/// Outcome of [QrAttendanceService.processScan]. Carries the marked
/// attendance plus the class info so the UI can show a rich confirmation.
class QrAttendanceResult {
  final String classId;
  final String className;
  final String studentId;
  final String studentName;
  final DateTime markedAt;

  const QrAttendanceResult({
    required this.classId,
    required this.className,
    required this.studentId,
    required this.studentName,
    required this.markedAt,
  });
}

/// Friendly errors thrown by [QrAttendanceService.processScan]. The UI relies
/// on the message string, so keep it human readable.
class QrAttendanceException implements Exception {
  final String message;
  const QrAttendanceException(this.message);

  @override
  String toString() => message;
}

/// Validates a QR scan from a student and records attendance directly.
///
/// Flow:
/// 1. Parse payload.
/// 2. Confirm the academy in the QR matches the student's active academy.
/// 3. Confirm the class still exists and is active.
/// 4. Confirm the student is enrolled in that class.
/// 5. Find a [ClassSchedule] for today that is inside the check-in window
///    (30 min before start until 1h after end).
/// 6. Skip if attendance is already recorded for this class/day.
/// 7. Call [AttendanceService.markPresent] (which also bumps attendanceCount
///    and dispatches milestone achievements).
class QrAttendanceService {
  final String academyId;
  late final ClassService _classService;
  late final AttendanceService _attendanceService;
  late final StudentService _studentService;

  QrAttendanceService(this.academyId) {
    _classService = ClassService(academyId);
    _attendanceService = AttendanceService(academyId);
    _studentService = StudentService(academyId);
  }

  Future<QrAttendanceResult> processScan({
    required String rawPayload,
    required String studentId,
    String? studentNameOverride,
    required String verifiedBy,
    required String verifiedByName,
  }) async {
    final QrPayload payload;
    try {
      payload = QrPayload.parse(rawPayload);
    } on FormatException catch (e) {
      throw QrAttendanceException(e.message);
    }

    if (payload.academyId != academyId) {
      throw const QrAttendanceException(
        'Este QR pertence a outra academia',
      );
    }

    final nowSeconds = DateTime.now().millisecondsSinceEpoch ~/ 1000;
    final ageSeconds = nowSeconds - payload.issuedAtSeconds;
    if (ageSeconds > kQrTokenTtl.inSeconds) {
      throw const QrAttendanceException(
        'QR expirado. Peca para o professor atualizar a tela.',
      );
    }
    if (ageSeconds < -kQrTokenTtl.inSeconds) {
      throw const QrAttendanceException(
        'Relogio do dispositivo desalinhado. Ajuste a hora.',
      );
    }

    final cls = await _classService.getById(payload.classId);
    if (cls == null || !cls.isActive) {
      throw const QrAttendanceException('Turma nao encontrada');
    }

    // Enrollment gate. Open classes (or legacy classes with no roster) accept
    // anyone in the academy; otherwise the student must appear in studentIds.
    if (!cls.acceptsCheckinFrom(studentId)) {
      throw const QrAttendanceException(
        'Voce nao esta matriculado nesta turma',
      );
    }

    // Student status gate: suspended/inactive/injured students cannot
    // self-check-in. Fetch happens here (not lazily later) so we fail fast
    // with a clearer message before any presence write is attempted.
    final student = await _studentService.getById(studentId);
    if (student == null) {
      throw const QrAttendanceException('Aluno nao encontrado');
    }
    if (student.status != StudentStatus.active) {
      throw const QrAttendanceException(
        'Sua matricula nao esta ativa. Procure a secretaria da academia.',
      );
    }

    final now = DateTime.now();
    final dayOfWeek = now.weekday % 7;
    final scheduleDate = DateTime(now.year, now.month, now.day, 12, 0, 0);

    ClassSchedule? matchingSchedule;
    for (final s in cls.schedule) {
      if (s.dayOfWeek != dayOfWeek) continue;
      final inWindow = isInCheckinWindow(
        startTime: s.startTime,
        endTime: s.endTime,
        date: scheduleDate,
      );
      if (inWindow) {
        matchingSchedule = s;
        break;
      }
    }

    if (matchingSchedule == null) {
      throw const QrAttendanceException(
        'Fora do horario de check-in desta turma',
      );
    }

    final studentName = (studentNameOverride != null && studentNameOverride.isNotEmpty)
        ? studentNameOverride
        : (student.fullName.isNotEmpty ? student.fullName : 'Aluno');

    // Concurrency safety lives inside markPresent (deterministic doc id +
    // transactional check-and-write). A pre-flight duplicate check here
    // would only add a redundant read.
    final Attendance attendance;
    try {
      attendance = await _attendanceService.markPresent(
        studentId: studentId,
        studentName: studentName,
        classId: cls.id,
        className: cls.name,
        verifiedBy: verifiedBy,
        verifiedByName: verifiedByName,
        date: scheduleDate,
        weight: cls.effectiveWeight(),
      );
    } catch (e) {
      if (e.toString().contains('marcado como presente')) {
        throw const QrAttendanceException(
          'Voce ja registrou presenca nesta aula',
        );
      }
      rethrow;
    }

    return QrAttendanceResult(
      classId: cls.id,
      className: cls.name,
      studentId: studentId,
      studentName: studentName,
      markedAt: attendance.createdAt,
    );
  }
}
